# Tokenizer
# These paths are used to save the tokenizer and vocab. Name accordingly.
tokenizer_type: hf # options: 'hf', 'sp'
tokenizer_path: PATH/TO/REPO/compute/dataset/tokenizers/tokenizer.model
vocab_path:  PATH/TO/REPO/compute/dataset/tokenizers/tokenizer.vocab
pad_id: -1 # defined later by tokenizer. NOTE: padding is disabled by default, see tokenizer.py
# With SP, this is defined later by tokenizer. With HF, this must be defined.
vocab_size: -1  

# Paths
# default_root_dir is the root model training directory; checkpoints, predictions, and logs will be saved here.
default_root_dir: PATH/TO/REPO/compute/runs/RUN/NAME/HERE
# which checkpoint to use, if any, for resuming training or inference
checkpoint_path: ~

# Dataset
# Name of hf hub dataset repo, if being used. Leave blank if not : ~
hf_dataset_name: wikitext
hf_dataset_config: wikitext-2-v1

# You may need to change filenames here if data came with split
raw_train_path: PATH/TO/REPO/compute/dataset/raw/DATA_DIRECTORY_NAME/train.csv
raw_val_path: PATH/TO/REPO/compute/dataset/raw/DATA_DIRECTORY_NAME/validation.csv
raw_test_path: PATH/TO/REPO/compute/dataset/raw/DATA_DIRECTORY_NAME/test.csv

# Train/validation/test split proportions
splits:
  - 0.7
  - 0.2
  - 0.1

# Dataset split, must be .pkl file
train_path: PATH/TO/REPO/compute/dataset/tokenized/train.pkl
val_path: PATH/TO/REPO/compute/dataset/tokenized/eval.pkl
test_path: PATH/TO/REPO/compute/dataset/tokenized/test.pkl

# GPU
use_slurm: true
accelerator: gpu
num_nodes: 1
devices: 8

# Train
gradient_accumulation_steps: 1
num_epochs: 10
lr: 1.0e-4 
gamma: 0.85
seed: 42
early_stopping: 5
save_top_k: 3
save_predictions_during_training: true
val_check_interval: 0.2
log_every_n_steps: 200
check_val_every_n_epoch: 1

# Inference
generation_path: PATH/TO/REPO/compute/dataset/raw/inference_text.txt
inference_dataset_path: PATH/TO/REPO/compute/dataset/tokenized/inference_data.pkl
inference_output_path: ~
max_gen_len: 50
temperature: ~
top_p: ~
repetition_penalty: ~

# Model
from_pretrained: false
model_name: ~ # * Pretrained model name, if using pretrained model
dim: 512
n_layers: 8
n_heads: 8
multiple_of: 256  # * make SwiGLU hidden layer size multiple of large power of 2
norm_eps: 1.0e-5
batch_size: 32
max_sequence_embeddings: 1024 # sequence_length
dim_k: ~
dim_v: ~
